grafana:
  image:
    registry: ghcr.io
    repository: miladarmani/mirror/grafana/grafana
    tag: "13.2.1-distroless"
  sidecar:
    image:
      registry: ghcr.io
      repository: miladarmani/mirror/kiwigrid/k8s-sidecar
      tag: "2.11.0"

kube-state-metrics:
  image:
    registry: ghcr.io
    repository: miladarmani/mirror/kube-state-metrics/kube-state-metrics
    tag: "v2.20.0"

prometheus-node-exporter:
  image:
    registry: ghcr.io
    repository: miladarmani/mirror/prometheus/node-exporter
    tag: "v1.12.1"
  resources:
    requests:
      memory: 32Mi
    limits:
      memory: 128Mi

prometheusOperator:
  image:
    registry: ghcr.io
    repository: miladarmani/mirror/prometheus-operator/prometheus-operator
    tag: "v0.93.1"
  prometheusConfigReloader:
    image:
      registry: ghcr.io
      repository: miladarmani/mirror/prometheus-operator/prometheus-config-reloader
      tag: "v0.93.1"

prometheus:
  prometheusSpec:
    image:
      registry: ghcr.io
      repository: miladarmani/mirror/prometheus/prometheus
      tag: "v3.14.0-distroless"
    nodeSelector:
      kubernetes.io/hostname: milad-master
    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 1536Mi
    retention: 3d

alertmanager:
  alertmanagerSpec:
    image:
      registry: ghcr.io
      repository: miladarmani/mirror/prometheus/alertmanager
      tag: "v0.34.0"
    nodeSelector:
      kubernetes.io/hostname: milad-master
    resources:
      requests:
        memory: 128Mi
      limits:
        memory: 512Mi
